@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute("edit 1 t/Parent")
activate logic
logic -> abp ++: parseCommand("edit 1 t/Parent")
create ecp
abp -> ecp
abp -> ecp ++: parse("1 t/Parent")
create ec
ecp -> ec ++: id, editPersonDescriptor
note right of ec
  Tags are appended.
  A bare t/ clears all tags.
end note
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

@enduml
